import csv
import os
import shutil
from document_schema import Document, ensure_unique_slug
from date_utils import format_date_iso

"""
for otoole.csv, which was generated by:
1. opening "Website SAVP.xlsx" in the Dropbox folder
2. editing with Numbers on mac (sigh)
3. exporting to csv.
"""


def main(data_file, content_file, output_file):
    """
    Generate HTML page from CSV and return Document objects.

    Args:
        data_file: Path to CSV file
        content_file: Path to content template HTML file
        output_file: Path to output HTML file

    Returns:
        list[Document]: List of all documents processed
    """
    assets_origin = '/Users/jsundram/Dropbox/Archive of CJS/Court Monitor/Blackman Jones/'
    pdf_files = {f: os.path.join(assets_origin, f) for f in os.listdir(assets_origin)}
    assets_destination = '../docs/assets/blackman/'
    os.makedirs(assets_destination, exist_ok=True)

    documents = []
    html_rows = []
    existing_slugs = set()

    with open(data_file, newline='', encoding='utf-8') as csvfile:
        next(csvfile) # page title
        next(csvfile) # blurb
        next(csvfile) # blank

        reader = csv.DictReader(csvfile)
        for row in reader:
            date = format_date_iso(row['Date'])
            title = row['Document'].strip()
            description = row['Description']
            filename = title + ".pdf"
            source = pdf_files[filename]
            shutil.copyfile(source, os.path.join(assets_destination, filename))
            file_path = f'assets/blackman/{filename}'
            url = f'./{file_path}'

            # Create Document object
            doc = Document(
                title=title,
                section='blackman',
                url=url,
                date=date,
                description=description,
                category='Court Monitor Report',
                file_path=file_path
            )

            # Ensure unique slug
            doc.slug = ensure_unique_slug(doc.slug, doc.section, existing_slugs)
            existing_slugs.add(f"{doc.section}-{doc.slug}")
            doc.document_url = f'documents/{doc.section}-{doc.slug}.html'

            documents.append(doc)

            # Generate HTML row
            html_rows.append(f"""
            <tr class="border-t border-t-[#d3dbe4]">
              <td class="align-top px-4 py-2 w-[150px] text-[#58728d] text-sm font-normal leading-normal">
                {date}
              </td>
              <td class="align-top px-4 py-2 w-[400px] text-[#101419] text-sm font-normal leading-normal">
                <a href="./{doc.document_url}" class="underline hover:text-blue-600">{title.upper()}</a>
              </td>
              <td class="align-top px-4 py-2 w-[400px] text-[#58728d] text-sm font-normal leading-normal">
                {description}
              </td>
            </tr>
            """)

    # Output the combined HTML
    rows_html = "\n".join(html_rows)

    # Load content template
    with open(content_file) as f:
        content_template = f.read()

    # Populate content template with rows
    content = content_template.replace('{rows}', rows_html)

    # Load base template
    with open('base-template.html') as f:
        template = f.read()

    # Populate template
    html = template.replace('{meta_title}', 'Blackman v. District of Columbia - Court Monitor Reports')
    html = html.replace('{meta_description}', 'Court Monitor reports for Blackman v. District of Columbia by Clarence J. Sundram.')
    html = html.replace('{canonical_url}', 'blackman.html')
    html = html.replace('{breadcrumb}', '')
    html = html.replace('{page_title}', 'Blackman v. District of Columbia')
    html = html.replace('{content}', content)
    html = html.replace('{path_prefix}', './')

    # Save result
    with open(output_file, 'w') as f:
        f.write(html)
        print(f"✅ HTML written to {output_file}")

    # Return documents for registry
    return documents


if __name__ == '__main__':
    main('../data/blackman.csv', 'blackman-content.html', '../docs/blackman.html')
