import csv
import dateparser
import os
import shutil

"""
for otoole.csv, which was generated by:
1. opening "Website SAVP.xlsx" in the Dropbox folder
2. editing with Numbers on mac (sigh)
3. exporting to csv.
"""

def format_date(date_str):
    # Converts M/D/YYYY to YYYY-MM-DD
    try:
        return dateparser.parse(date_str).strftime('%Y-%m-%d')
    except ValueError:
        print(f"error parsing: {date_str}")
        return date_str  # Fallback if date is malformed


def main(data_file, template_file, output_file):
    rows = []
    with open(data_file, newline='', encoding='utf-8') as csvfile:
        reader = csv.DictReader(csvfile)
        for row in reader:
            date = format_date(row['DATE'])
            action = row['ACTION']
            title = row['News Coverage']
            url = row['URL']

            rows.append(f"""
            <tr class="border-t border-t-[#d3dbe4]">
              <td class="align-top px-4 py-2 w-[150px] text-[#58728d] text-sm font-normal leading-normal">
                {date}
              </td>
              <td class="align-top px-4 py-2 w-[600px] text-[#58728d] text-sm font-normal leading-normal">
                {action}
              </td>
              <td class="align-top px-4 py-2 w-[200px] text-[#101419] text-sm font-normal leading-normal">
                <a href="{url}" target="_blank" class="underline hover:text-blue-600">{title.upper()}</a>
              </td>
            </tr>
            """)

    # Output the combined HTML
    rows_html = "\n".join(rows)

    # Load template
    with open(template_file) as f:
        template = f.read()

    # Populate template
    template = template.replace('{rows}', rows_html)

    # Save result
    with open(output_file, 'w') as f:
        f.write(template)
        print(f"✅ HTML written to {output_file}")


if __name__ == '__main__':
    main('../data/otoole-timeline.csv', 'otoole-timeline-template.html', '../docs/otoole-timeline.html')
