import csv
import dateparser
from document_schema import Document, ensure_unique_slug

"""
for otoole.csv, which was generated by:
1. opening "Website SAVP.xlsx" in the Dropbox folder
2. editing with Numbers on mac (sigh)
3. exporting to csv.
"""

def format_date(date_str):
    # Converts M/D/YYYY to YYYY-MM-DD
    try:
        return dateparser.parse(date_str).strftime('%Y-%m-%d')
    except ValueError:
        print(f"error parsing: {date_str}")
        return date_str  # Fallback if date is malformed


def main(data_file, content_file, output_file):
    """
    Generate HTML page from CSV and return Document objects.

    Args:
        data_file: Path to CSV file
        content_file: Path to content template HTML file
        output_file: Path to output HTML file

    Returns:
        list[Document]: List of all documents processed
    """
    documents = []
    html_rows = []
    existing_slugs = set()

    with open(data_file, newline='', encoding='utf-8') as csvfile:
        reader = csv.DictReader(csvfile)
        for row in reader:
            date = format_date(row['DATE'])
            action = row['ACTION']
            title = row['News Coverage']
            url = row['URL']

            # Create Document object
            doc = Document(
                title=title,
                section='otoole-timeline',
                url=url,
                date=date,
                description=action,
                category='Timeline Event'
            )

            # Ensure unique slug
            doc.slug = ensure_unique_slug(doc.slug, doc.section, existing_slugs)
            existing_slugs.add(f"{doc.section}-{doc.slug}")
            doc.document_url = f'documents/{doc.section}-{doc.slug}.html'

            documents.append(doc)

            # Generate HTML row
            html_rows.append(f"""
            <tr class="border-t border-t-[#d3dbe4]">
              <td class="align-top px-4 py-2 w-[150px] text-[#58728d] text-sm font-normal leading-normal">
                {date}
              </td>
              <td class="align-top px-4 py-2 w-[600px] text-[#58728d] text-sm font-normal leading-normal">
                {action}
              </td>
              <td class="align-top px-4 py-2 w-[200px] text-[#101419] text-sm font-normal leading-normal">
                <a href="./{doc.document_url}" class="underline hover:text-blue-600">{title.upper()}</a>
              </td>
            </tr>
            """)

    # Output the combined HTML
    rows_html = "\n".join(html_rows)

    # Load content template
    with open(content_file) as f:
        content_template = f.read()

    # Populate content template with rows
    content = content_template.replace('{rows}', rows_html)

    # Load base template
    with open('base-template.html') as f:
        template = f.read()

    # Populate template
    html = template.replace('{meta_title}', "O'Toole v. Cuomo - Timeline")
    html = html.replace('{meta_description}', "Timeline of events and actions in O'Toole v. Cuomo with related news coverage.")
    html = html.replace('{canonical_url}', 'otoole-timeline.html')
    html = html.replace('{breadcrumb}', '')
    html = html.replace('{page_title}', "O'Toole v. Cuomo - Timeline")
    html = html.replace('{content}', content)
    html = html.replace('{path_prefix}', './')

    # Save result
    with open(output_file, 'w') as f:
        f.write(html)
        print(f"✅ HTML written to {output_file}")

    # Return documents for registry
    return documents


if __name__ == '__main__':
    main('../data/otoole-timeline.csv', 'otoole-timeline-content.html', '../docs/otoole-timeline.html')
