import csv
import os
import shutil
from document_schema import Document, ensure_unique_slug
from date_utils import format_date_iso

"""
for savp.csv, which was generated by:
1. opening "Website SAVP.xlsx" in the Dropbox folder
2. editing with Numbers on mac (sigh)
3. exporting to csv.
4. opening in vim,
5. Fixing the smart quotes in the bio blurb
6. Fixing the apostrophe in "Ending Abuse ..."
7. Fixing the apostrophe in the podcast episode
8. replacing the smart quotes with double-regular quotes (one to fix, one to escape) in the podcast episodes
"""


def main(data_file, content_file, output_file):
    """
    Generate HTML page from CSV and return Document objects.

    Args:
        data_file: Path to CSV file
        content_file: Path to content template HTML file
        output_file: Path to output HTML file

    Returns:
        list[Document]: List of all documents processed
    """
    # destination for copied files:
    assets_origin = '/Users/jsundram/Dropbox/Archive of CJS/Special Advisor/'
    pdf_files = {f.lower(): os.path.join(assets_origin, f) for f in os.listdir(assets_origin)}
    assets_destination = '../docs/assets/savp/'

    documents = []
    html_rows = []
    existing_slugs = set()

    with open(data_file, newline='', encoding='utf-8') as csvfile:
        next(csvfile) # page title
        blurb = next(csvfile).strip().strip(',').strip('"')

        reader = csv.DictReader(csvfile)
        for row in reader:
            date = format_date_iso(row['Date'])
            media = row['Type']
            title = row['Title']
            description = row['Description']
            url = row['URL']
            file_path = ""

            if url == 'PDF':
                key = title.lower().replace(':', '-') + ".pdf"
                source = pdf_files[key]
                shutil.copyfile(source, os.path.join(assets_destination, key))
                file_path = f'assets/savp/{key}'
                url = f'./{file_path}'

            # Create Document object
            doc = Document(
                title=title,
                section='savp',
                url=url,
                date=date,
                description=description,
                category=media,
                file_path=file_path
            )

            # Ensure unique slug
            doc.slug = ensure_unique_slug(doc.slug, doc.section, existing_slugs)
            existing_slugs.add(f"{doc.section}-{doc.slug}")
            doc.document_url = f'documents/{doc.section}-{doc.slug}.html'

            documents.append(doc)

            # Generate HTML row
            html_rows.append(f"""
            <tr class="border-t border-t-[#d3dbe4]">
              <td class="align-top px-4 py-2 w-[150px] text-[#58728d] text-sm font-normal leading-normal">
                {date}
              </td>
              <td class="align-top px-4 py-2 w-60 text-sm font-normal leading-normal">
                <button class="flex min-w-[84px] max-w-[480px] cursor-pointer items-center justify-center overflow-hidden rounded-full h-8 px-4 bg-[#e9edf1] text-[#101419] text-sm font-medium leading-normal w-full">
                  <span class="truncate">{media}</span>
                </button>
              </td>
              <td class="align-top px-4 py-2 w-[200px] text-[#101419] text-sm font-normal leading-normal">
                <a href="./{doc.document_url}" class="underline hover:text-blue-600">{title.upper()}</a>
              </td>
              <td class="align-top px-4 py-2 w-[400px] text-[#58728d] text-sm font-normal leading-normal">
                {description}
              </td>
            </tr>
            """)

    # Output the combined HTML
    rows_html = "\n".join(html_rows)

    # Load content template
    with open(content_file) as f:
        content_template = f.read()

    # Populate content template with rows
    content = content_template.replace('{rows}', rows_html)

    # Load base template
    with open('base-template.html') as f:
        template = f.read()

    # Populate template
    html = template.replace('{meta_title}', 'Special Advisor to the Governor')
    html = html.replace('{meta_description}', 'Publications and presentations from Clarence J. Sundram\'s work as Special Advisor to the Governor on the Mentally Disabled.')
    html = html.replace('{canonical_url}', 'special-advisor.html')
    html = html.replace('{breadcrumb}', '')
    html = html.replace('{page_title}', 'Special Advisor to the Governor')
    html = html.replace('{content}', content)
    html = html.replace('{path_prefix}', './')

    # Save result
    with open(output_file, 'w') as f:
        f.write(html)
        print(f"✅ HTML written to {output_file}")

    # Return documents for registry
    return documents


if __name__ == '__main__':
    main('../data/savp.csv', 'savp-content.html', '../docs/special-advisor.html')
